name: Release gem

on:
  workflow_dispatch:

jobs:
  release:
    uses: jenshenny/gem-publishing-workflow/.github/workflows/release.yml@main
    permissions:
      contents: write
      id-token: write
